### ISSUE TITLE
can.route.attr({}, true) throws an error

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-route#98]
Passing an object as the first argument to `can.route.attr` and anything as the second argument throws an error:
```
can.route.attr({
  page: 'foo'
}, true);
```

```
error TypeError: Cannot define property _instanceDefinitions, object is not extensible
    at Function.defineProperty (<anonymous>)
    at Object.defineExpando (https://unpkg.com/can@3.9.0/dist/global/can.all.js:14845:24)
    at DefineMap.setKeyValue (https://unpkg.com/can@3.9.0/dist/global/can.all.js:14939:37)
    at Object.setKeyValue (https://unpkg.com/can@3.9.0/dist/global/can.all.js:1042:36)
    at DefineMap.attrHelper (https://unpkg.com/can@3.9.0/dist/global/can.all.js:15725:28)
    at Function.canRoute.attr (https://unpkg.com/can@3.9.0/dist/global/can.all.js:16107:27)
```

Here is an example: http://jsbin.com/dipiwikida/1/edit?js,console.

I think this is happening because people were previously using can-map and wanted to set the `removeOthers` flag and have now switched their appViewModel to DefineMap.

**Comment by phillipskevin** [comment]
A workaround is to use `can.route.data.set(..., true)` if you are using a DefineMap to back can-route.

**Comment by roemhildtg** [comment]
I was running into this when I was binding to a route that was using a `defineMap.extend`. I fixed it by using `{seal:false}` on the extended define map.

**Comment by phillipskevin** [comment]
Related to https://github.com/canjs/can-define/issues/245.
